//央视
cctv.webs.push(new TVWeb("央视网","中国","https://www.cctv.com/"))

//广东
gd.webs.push(new TVWeb("荔枝网","广东","https://www.gdtv.cn/"))
gd.webs.push(new TVWeb("广视网","广东广州","https://www.gztv.com/"))
gd.webs.push(new TVWeb("壹深圳","广东深圳","https://www.sztv.com.cn/"))
gd.webs.push(new TVWeb("珠海网","广东珠海","https://www.hizh.cn/"))
gd.webs.push(new TVWeb("橄榄网","广东汕头","http://strtv.dahuawang.com/index.shtml"))
gd.webs.push(new TVWeb("佛山电视台","广东佛山","https://www.fstv.com.cn/"))
gd.webs.push(new TVWeb("韶关市广播电视台","广东韶关","http://sgbtv.sgmsw.cn/"))
gd.webs.push(new TVWeb("河源网络广播电视台","广东河源","https://www.hyrtv.cn/"))
gd.webs.push(new TVWeb("梅视网","广东梅州","http://www.gdmztv.com/"))
gd.webs.push(new TVWeb("东方传媒网","广东惠州","http://www.hzrtv.cn/"))
gd.webs.push(new TVWeb("汕尾广播电视台","广东汕尾","http://www.swrtv.com/"))
gd.webs.push(new TVWeb("中山之窗","广东中山","http://www.zsbtv.com.cn/"))
gd.webs.push(new TVWeb("江门广播电视台","广东江门","http://www.jmtv.cn/"))
gd.webs.push(new TVWeb("阳江视听网","广东阳江","https://www.yjtvw.com/"))
gd.webs.push(new TVWeb("湛江广视网","广东湛江","http://www.zjwtv.com/"))
gd.webs.push(new TVWeb("茂名视听网","广东茂名","http://www.mmstw.com/"))
gd.webs.push(new TVWeb("肇庆广播电视台","广东肇庆","http://www.zqgd.net"))
gd.webs.push(new TVWeb("潮州广播电视网","广东潮州","http://www.czbtv.com/"))
gd.webs.push(new TVWeb("揭阳声屏网","广东揭阳","http://www.jyrtv.tv/"))

//香港
hk.webs.push(new TVWeb("TVB翡翠台","香港","https://www.tvb.com/"))
hk.webs.push(new TVWeb("ATV亚洲电视本港台","香港","http://www.hkatv.com/"))
hk.webs.push(new TVWeb("凤凰卫视","香港","https://phtv.ifeng.com/"))
hk.webs.push(new TVWeb("HKS香港卫视","香港","http://www.hkstv.tv/"))

//澳门
mo.webs.push(new TVWeb("澳门有线电视","澳门","http://www.macaucabletv.com/"))

//安徽
ah.webs.push(new TVWeb("安徽网络广播电视台","安徽","http://www.ahtv.cn/"))
ah.webs.push(new TVWeb("合肥广播电视台","安徽合肥","https://www.hfbtv.com/"))
ah.webs.push(new TVWeb("皖江明珠网","安徽芜湖","http://www.wuhubtv.com/"))
ah.webs.push(new TVWeb("铜陵网络台","安徽铜陵","http://www.tlbts.com/"))
ah.webs.push(new TVWeb("黄山新闻网","安徽黄山","http://www.hsnewsnet.com/"))
ah.webs.push(new TVWeb("阜阳公众网","安徽阜阳","http://www.fytv.com.cn/"))
ah.webs.push(new TVWeb("宿州新闻网","安徽宿州","http://www.ahsz.tv/"))
ah.webs.push(new TVWeb("滁州广播电视我","安徽滁州","http://www.cztv.cc/"))
ah.webs.push(new TVWeb("六安广播电视网","安徽六安","http://www.china-latv.com/"))
ah.webs.push(new TVWeb("宣城新闻网","安徽宣城","http://www.newsxc.com/"))
ah.webs.push(new TVWeb("亳州视听网","安徽亳州","http://www.ahbztv.com/"))

//北京
bj.webs.push(new TVWeb("北京网络广播电视台","北京","https://www.brtn.cn/"))

//重庆
cq.webs.push(new TVWeb("重庆网络广播电视台","重庆","https://www.cbg.cn/"))
cq.webs.push(new TVWeb("渝中网络广播电视台","重庆渝中","https://yuzhong.cbg.cn/"))
cq.webs.push(new TVWeb("三峡传媒网","重庆万州","http://www.sxcm.net/"))
cq.webs.push(new TVWeb("大渡口网络广播电视台","重庆大渡口","https://dadukou.cbg.cn/"))
cq.webs.push(new TVWeb("江北网络广播电视台","重庆江北","http://qxcms.cbg.cn/jb/"))
cq.webs.push(new TVWeb("沙坪坝网络广播电视台","重庆沙坪坝","https://shapingba.cbg.cn/"))
cq.webs.push(new TVWeb("九龙坡网络广播电视台","重庆九龙坡","https://jiulongpo.cbg.cn/"))
cq.webs.push(new TVWeb("北碚网络广播电视台","重庆北碚","https://beibei.cbg.cn/"))
cq.webs.push(new TVWeb("綦江手机台","重庆綦江","https://qijiang.cbg.cn/"))
cq.webs.push(new TVWeb("大足网络广播电视台","重庆大足","https://dazu.cbg.cn/"))
cq.webs.push(new TVWeb("渝北融媒体中心","重庆渝北","https://yubei.cbg.cn/"))
cq.webs.push(new TVWeb("巴南网络广播电视台","重庆巴南","https://banan.cbg.cn/"))
cq.webs.push(new TVWeb("黔江网络广播电视台","重庆黔江","https://qianjiang.cbg.cn/"))
cq.webs.push(new TVWeb("长寿网络广播电视台","重庆长寿","https://changshou.cbg.cn/"))
cq.webs.push(new TVWeb("江津网络广播电视台","重庆江津","https://jiangjin.cbg.cn/"))
cq.webs.push(new TVWeb("合川网络电视台","重庆合川","http://www.jrhcw.com/"))
cq.webs.push(new TVWeb("永川广播电视台","重庆永川","http://tv.yongchuan.cn/"))
cq.webs.push(new TVWeb("南川网","重庆南川","http://video.cqncnews.com/zhiyaonilaixiu/"))
cq.webs.push(new TVWeb("璧山网络广播电视台","重庆璧山","https://bishan.cbg.cn/"))
cq.webs.push(new TVWeb("铜梁网络广播电视台","重庆铜梁","https://tongliang.cbg.cn/"))
cq.webs.push(new TVWeb("潼南网络广播电视台","重庆潼南","https://tongnan.cbg.cn/"))
cq.webs.push(new TVWeb("荣昌网络广播电视台","重庆荣昌","https://rongchang.cbg.cn/"))
cq.webs.push(new TVWeb("开州网络广播电视台","重庆开州","https://kaizhou.cbg.cn/"))
cq.webs.push(new TVWeb("梁平网络广播电视台","重庆梁平","https://liangping.cbg.cn/"))
cq.webs.push(new TVWeb("武隆区融媒体中心","重庆武隆","https://wulong.cbg.cn/"))
cq.webs.push(new TVWeb("城口县融媒体中心","重庆城口","https://chengkou.cbg.cn/"))
cq.webs.push(new TVWeb("丰都网络广播电视台","重庆丰都","https://fengdu.cbg.cn/"))
cq.webs.push(new TVWeb("垫江县融媒体中心","重庆垫江","https://dianjiang.cbg.cn/"))
cq.webs.push(new TVWeb("忠县网络广播电视台","重庆忠县","https://zhongxian.cbg.cn/"))
cq.webs.push(new TVWeb("云阳网","重庆云阳","http://www.yunyangwang.com/"))
cq.webs.push(new TVWeb("奉节网络广播电视台","重庆奉节","https://fengjie.cbg.cn/"))
cq.webs.push(new TVWeb("巫山网络广播电视台","重庆巫山","http://www.cqwstv.cn/"))
cq.webs.push(new TVWeb("巫溪新闻网","重庆巫溪","http://www.cqwxnews.net/"))

//福建
fj.webs.push(new TVWeb("福建网络广播电视台","福建","https://www.fjtv.net/"))
fj.webs.push(new TVWeb("福州明珠","福建福州","http://www.zohi.tv/"))
fj.webs.push(new TVWeb("厦门广电网","福建厦门","https://xmtv.cn/"))
fj.webs.push(new TVWeb("漳州电视台","福建漳州市","https://www.zztv.fj.cn/"))
fj.webs.push(new TVWeb("泉视界","福建泉州","https://www.qztv.cn/"))
fj.webs.push(new TVWeb("莆田广播电视台","福建莆田","https://www.ptbtv.com/"))
fj.webs.push(new TVWeb("红土地网","福建龙岩","http://www.lytv.net.cn/"))
fj.webs.push(new TVWeb("宁德网","福建宁德","http://www.ndwww.cn/"))

//甘肃
gs.webs.push(new TVWeb("丝路明珠网","甘肃","https://www.gstv.com.cn/"))
gs.webs.push(new TVWeb("兰云网","甘肃兰州","https://www.lztv.tv/"))
gs.webs.push(new TVWeb("嘉峪关广播电视台","甘肃嘉峪关","http://www.0937tv.com/"))
gs.webs.push(new TVWeb("金昌广播电视网","甘肃金昌","http://www.jcnrtv.com/"))
gs.webs.push(new TVWeb("白银视线","甘肃白银","http://www.bygd.cn/"))
gs.webs.push(new TVWeb("直播天水","甘肃天水","http://www.zhibotianshui.com/"))
gs.webs.push(new TVWeb("天马在线","甘肃武威","http://www.tv0935.com/"))
gs.webs.push(new TVWeb("张掖视图网","甘肃张掖","https://www.zytv.cc/"))
gs.webs.push(new TVWeb("酒泉广播电视台","甘肃酒泉","https://www.gsjqtv.com/"))
gs.webs.push(new TVWeb("庆阳广播电视台","甘肃庆阳","https://www.gsqytv.com.cn/"))
gs.webs.push(new TVWeb("新甘南","甘肃甘南","http://www.gnrtv.com/m/index.php"))

//广西
gx.webs.push(new TVWeb("广西网络广播电视台","广西","https://www.gxtv.cn/"))
gx.webs.push(new TVWeb("老友网","广西南宁","http://www.nntv.cn/"))
gx.webs.push(new TVWeb("柳州广播电视网","广西柳州","https://www.lzgd.com.cn/"))
gx.webs.push(new TVWeb("桂视网","广西桂林","https://www.gltvs.com/"))
gx.webs.push(new TVWeb("西江在线网","广西梧州","http://www.onlinexijiang.com/"))
gx.webs.push(new TVWeb("北海广播电视网","广西北海","http://www.bhtv.cc/"))
gx.webs.push(new TVWeb("崇左广播电视网","广西崇左","http://www.gxcztv.cn/"))
gx.webs.push(new TVWeb("玉林广播电视网","广西玉林","yltvb.com"))
gx.webs.push(new TVWeb("百色广播电视网","广西百色","http://www.gxbstv.com/"))
gx.webs.push(new TVWeb("河池视频网","广西河池","http://www.hcbtv.com/"))
gx.webs.push(new TVWeb("钦州新闻网","广西钦州","http://www.gxqzxw.com/"))
gx.webs.push(new TVWeb("今日防城港","广西防城港","http://www.fcgtvb.com/index"))
gx.webs.push(new TVWeb("西江传媒","广西贵港","http://www.xijiangtv.com/"))

//贵州
gz.webs.push(new TVWeb("贵州网络广播电视台","贵州","https://www.gzstv.com/"))
gz.webs.push(new TVWeb("贵阳网络广播电视台","贵州贵阳","https://www.gystv.com/"))
gz.webs.push(new TVWeb("视听凉都","贵州六盘水","http://m.lpsntv.com/"))
gz.webs.push(new TVWeb("安顺市广播电视台","贵州安顺","http://www.gzastv.com/"))
gz.webs.push(new TVWeb("黔东南广电","贵州黔东南","http://www.qdntv.com/"))
gz.webs.push(new TVWeb("黔西南广播电视台","贵州黔西南","http://www.qxndt.com/"))

//海南
hi.webs.push(new TVWeb("海南网络广播电视台","海南","http://www.hnntv.cn/"))
hi.webs.push(new TVWeb("海广网","海南海口","http://www.hkbtv.cn/"))
hi.webs.push(new TVWeb("在天涯网","海南三亚","http://www.zaity.tv/"))
hi.webs.push(new TVWeb("儋州广电","海南儋州","http://www.danzhoutv.net/"))

//河北
he.webs.push(new TVWeb("河北网络广播电视台","河北","https://www.hebtv.com/"))
he.webs.push(new TVWeb("石家庄网络广播电视台","河北石家庄","http://www.sjzntv.cn/"))
he.webs.push(new TVWeb("唐山广播电视台","河北唐山","http://www.tsr.he.cn/"))
he.webs.push(new TVWeb("秦皇岛传媒网","河北秦皇岛","http://www.qhdcm.com/"))
he.webs.push(new TVWeb("邯郸广电网","河北邯郸","http://www.hdbs.cn/"))
he.webs.push(new TVWeb("邢台电视台","河北邢台","http://www.xttv.com.cn/"))
he.webs.push(new TVWeb("保定广电网","河北保定","https://www.bdgdw.com/"))
he.webs.push(new TVWeb("张家口网络广播电视台","河北张家口","https://www.zjkgdcs.com/"))
he.webs.push(new TVWeb("承德广播电视网","河北承德","https://www.chengdetv.com/"))
he.webs.push(new TVWeb("沧州广电网","河北沧州","http://www.czgd.tv/"))
he.webs.push(new TVWeb("网上廊坊","河北廊坊","http://www.lfnrtv.com/"))
he.webs.push(new TVWeb("衡水广播电视网","河北衡水","http://www.hsrtv.cn/"))

//河南
ha.webs.push(new TVWeb("大象网","河南","https://www.hntv.tv/"))
ha.webs.push(new TVWeb("郑州广播电视台","河南郑州","http://www.zztv.tv/"))
ha.webs.push(new TVWeb("开封广播电视台","河南开封","http://www.kftv.net.cn/"))
ha.webs.push(new TVWeb("洛阳广播电视台","河南洛阳","http://www.lytv.com.cn/"))
ha.webs.push(new TVWeb("平顶山广播电视台","河南平顶山","http://www.pdsrtv.cn/"))
ha.webs.push(new TVWeb("安阳新闻网","河南安阳","http://www.aynews.net.cn/"))
ha.webs.push(new TVWeb("鹤壁网","河南鹤壁","http://www.hebitv.com/"))
ha.webs.push(new TVWeb("新乡新闻网","河南新乡","http://www.tv373.com/"))
ha.webs.push(new TVWeb("焦作广播电视网","河南焦作","http://www.jzrt.com/"))
ha.webs.push(new TVWeb("许昌广播电视网","河南许昌","http://www.xctv.cn"))
ha.webs.push(new TVWeb("漯河网","河南漯河","http://www.luohe.tv/"))
ha.webs.push(new TVWeb("三门峡广播电视网","河南三门峡","http://www.smxtv.com.cn/"))
ha.webs.push(new TVWeb("商丘网","河南商丘","http://sqtv.net/"))
ha.webs.push(new TVWeb("周口网","河南周口","http://www.zkxww.com/"))
ha.webs.push(new TVWeb("驻马店广视网","河南驻马店","http://www.zmdtvw.cn/"))
ha.webs.push(new TVWeb("南阳广播电视台","河南南阳","https://www.nydt.cn/"))
ha.webs.push(new TVWeb("信阳电视网","河南信阳","https://www.xytv.cn/"))

//黑龙江
hl.webs.push(new TVWeb("黑龙江网络广播电视台","黑龙江","https://www.hljtv.com/"))
hl.webs.push(new TVWeb("哈尔滨广播电视台","黑龙江哈尔滨","https://www.hrbtv.net/"))
hl.webs.push(new TVWeb("齐齐哈尔新闻网","黑龙江齐齐哈尔","https://www.qqhrnews.com/"))
hl.webs.push(new TVWeb("鹤岗市广播电视台","黑龙江鹤岗","http://www.hgdst.org.cn/"))
hl.webs.push(new TVWeb("大庆广播电视台","黑龙江大庆","https://www.dqrtv.cn/"))
hl.webs.push(new TVWeb("伊春广电网","黑龙江伊春","http://www.yichuntv.com/"))
hl.webs.push(new TVWeb("佳木斯广播电视台","黑龙江佳木斯","https://jmsdst.com/"))
hl.webs.push(new TVWeb("七台河广播电视台网","黑龙江七台河","https://www.qthtv.net/"))

//湖北
hb.webs.push(new TVWeb("长江云","湖北","http://news.hbtv.com.cn/"))
hb.webs.push(new TVWeb("黄鹤云","湖北武汉","http://www.whtv.com.cn/"))
hb.webs.push(new TVWeb("黄石广播电视台","湖北黄石","http://www.hsgd.net.cn/"))
hb.webs.push(new TVWeb("十堰广电网","湖北十堰","https://www.syiptv.com/"))
hb.webs.push(new TVWeb("三峡广电网","湖北宜昌","http://www.3xgd.com/"))
hb.webs.push(new TVWeb("襄阳广电网","湖北襄阳","http://www.xyrtv.com/"))
hb.webs.push(new TVWeb("荆彩网","湖北荆门","http://www.jmtv.com.cn/"))
hb.webs.push(new TVWeb("荆州网络电视","湖北荆州","http://v.jznews.com.cn/"))
hb.webs.push(new TVWeb("咸宁广电网","湖北咸宁","http://www.hbxntv.com/"))
hb.webs.push(new TVWeb("恩施电视台","湖北恩施","http://enshi.cjyun.org/"))

//湖南
hn.webs.push(new TVWeb("芒果TV","湖南","https://www.mgtv.com/"))
hn.webs.push(new TVWeb("长沙广播电视台","湖南长沙","https://www.csbtv.com/"))
hn.webs.push(new TVWeb("株洲传媒网","湖南株洲","http://www.zzbtv.com/"))
hn.webs.push(new TVWeb("湘潭传媒网","湖南湘潭","http://www.hnxttv.com/"))
hn.webs.push(new TVWeb("衡阳广电网","湖南衡阳","http://www.hydst.com/"))
hn.webs.push(new TVWeb("邵阳传媒网","湖南邵阳","http://www.sytv.net.cn/"))
hn.webs.push(new TVWeb("岳阳新闻网","湖南岳阳","https://www.0730news.com/"))
hn.webs.push(new TVWeb("张家界广播电视台","湖南张家界","http://www.zjjrtv.com/"))
hn.webs.push(new TVWeb("益阳广播电视在线","湖南益阳","https://www.yyrtv.com/"))
hn.webs.push(new TVWeb("娄底网络电视台","湖南娄底","http://www.hnldw.cn/"))
hn.webs.push(new TVWeb("南国郴州网","湖南郴州","http://www.ngcz.tv/"))
hn.webs.push(new TVWeb("永州市广播电视台","湖南永州","http://www.21ytv.com/"))
hn.webs.push(new TVWeb("怀化市广播电视台","湖南怀化","http://www.0745tv.com/"))

//吉林
jl.webs.push(new TVWeb("吉视网","吉林","http://www.jlntv.cn/newpc/"))
jl.webs.push(new TVWeb("长春广播电视台","吉林长春","http://www.chinactv.com/"))
jl.webs.push(new TVWeb("四平广播电视网","吉林四平","http://evfh-www.plus.jlntv.cn/"))
jl.webs.push(new TVWeb("辽源广播电视台","吉林辽源","http://www.0437tv.com/"))
jl.webs.push(new TVWeb("通化网络广播电视","吉林通化","http://10c9-www.plus.jlntv.cn/"))
jl.webs.push(new TVWeb("松原广播电视网","吉林松原","http://uogz-www.plus.jlntv.cn/"))
jl.webs.push(new TVWeb("白城电视网","吉林白城","http://ente-www.plus.jlntv.cn/"))
jl.webs.push(new TVWeb("延边信息港","吉林延边","http://www.yb983.com/"))

//江苏
js.webs.push(new TVWeb("荔枝网","江苏","https://www.jstv.com/"))
js.webs.push(new TVWeb("南京广播电视台","江苏南京","http://www.nbs.cn/"))
js.webs.push(new TVWeb("无锡广播电视台","江苏无锡","http://btv.thmz.com/"))
js.webs.push(new TVWeb("淮海网","江苏徐州","https://www.huaihai.tv/"))
js.webs.push(new TVWeb("中吴网","江苏常州","http://www.cztv.tv/"))
js.webs.push(new TVWeb("苏州广播电视总台","江苏苏州","http://www.csztv.cn/"))
js.webs.push(new TVWeb("江海明珠网","江苏南通","https://www.ntjoy.com/"))
js.webs.push(new TVWeb("连云港传媒网","江苏连云港","http://www.lyg1.com/"))
js.webs.push(new TVWeb("淮安视听网","江苏淮安","http://www.habctv.com/"))
js.webs.push(new TVWeb("盐城网","江苏盐城","https://www.0515yc.cn/"))
js.webs.push(new TVWeb("扬帆网","江苏扬州","https://pc.96189.com/"))
js.webs.push(new TVWeb("镇江传媒网","江苏镇江","https://www.zjmc.tv/"))
js.webs.push(new TVWeb("泰州广播电视台","江苏泰州","http://www.tz2100.com/"))
js.webs.push(new TVWeb("宿迁网络电视","江苏宿迁","http://tv.xichu.net/"))

//江西
jx.webs.push(new TVWeb("江西网络广播电视台","江西","https://www.jxntv.cn/"))
jx.webs.push(new TVWeb("南昌广播电视台","江西南昌","https://www.nctv.net.cn/"))
jx.webs.push(new TVWeb("九江视听网","江西九江","http://www.jjntv.cn/"))
jx.webs.push(new TVWeb("上饶视听网","江西上饶","http://0793.tv/"))
jx.webs.push(new TVWeb("抚州新闻网","江西抚州","http://www.zgfznews.com/"))
jx.webs.push(new TVWeb("宜春传媒网","江西宜春","http://www.ycstv.com/"))
jx.webs.push(new TVWeb("爱吉安网","江西吉安","http://www.ijatv.com/"))
jx.webs.push(new TVWeb("赣州网络台","江西赣州","http://www.jxgztv.com/"))
jx.webs.push(new TVWeb("景德镇市广播电视台","江西景德镇","http://www.jdztv.net/"))
jx.webs.push(new TVWeb("萍乡频道","江西萍乡","http://px.jxntv.cn/"))
jx.webs.push(new TVWeb("每日新余视听网","江西新余","http://www.jxxydaily.cn/"))
jx.webs.push(new TVWeb("鹰潭频道","江西鹰潭","http://yt.jxntv.cn/"))

//辽宁
ln.webs.push(new TVWeb("辽宁广播电视台","辽宁","http://www.lntv.cn/"))
ln.webs.push(new TVWeb("沈阳市广播电视台","辽宁沈阳","http://www.csytv.com/"))
ln.webs.push(new TVWeb("大连新闻网","辽宁大连","http://www.dltv.cn/"))
ln.webs.push(new TVWeb("抚顺新闻网","辽宁抚顺","http://www.fs024.com/"))
ln.webs.push(new TVWeb("锦州广播电视台","辽宁锦州","http://www.jzgbdst.cn/m/"))
ln.webs.push(new TVWeb("铁岭广播电视台","辽宁铁岭","http://www.tielingtv.com/"))
ln.webs.push(new TVWeb("葫芦岛广播电视网","辽宁葫芦岛","http://www.hldbtv.com/"))

//内蒙古
nm.webs.push(new TVWeb("内蒙古网络广播电视台","内蒙古","http://www.nmtv.cn/"))
nm.webs.push(new TVWeb("呼和浩特广播电视台","内蒙古呼和浩特","http://www.0471tv.org.cn/"))
nm.webs.push(new TVWeb("包头广播电视台","内蒙古包头","http://www.btgdt.com/"))
nm.webs.push(new TVWeb("乌海广播电视台","内蒙古乌海","http://www.nmwhrtv.com/"))
nm.webs.push(new TVWeb("赤峰广播电视网","内蒙古赤峰","http://www.cfradio.cn/"))
nm.webs.push(new TVWeb("鄂尔多斯广播电视台","内蒙古鄂尔多斯","https://erdszs.org.cn/"))
nm.webs.push(new TVWeb("呼伦贝尔广播电视台","内蒙古呼伦贝尔","http://www.hrtonline.cn/"))
nm.webs.push(new TVWeb("乌兰察布广播电视台","内蒙古乌兰察布","https://www.wrbtv.cn/"))
nm.webs.push(new TVWeb("兴安广播电视台","内蒙古兴安","http://www.xingantv.com/"))
nm.webs.push(new TVWeb("阿拉善盟广播电视台","内蒙古阿拉善","http://www.artv.net.cn/"))

//宁夏
nx.webs.push(new TVWeb("宁夏广播电视台","宁夏","http://www.nxtv.com.cn/"))
nx.webs.push(new TVWeb("银川新闻网","宁夏银川","http://www.ycen.com.cn/"))
nx.webs.push(new TVWeb("石嘴山新闻网","宁夏石嘴山","http://www.szsnews.com/"))
nx.webs.push(new TVWeb("吴忠网","宁夏吴忠","https://www.kanwz.net/"))
nx.webs.push(new TVWeb("固原新闻网","宁夏固原","https://www.gyxww.net/"))
nx.webs.push(new TVWeb("中卫新闻网","宁夏中卫","http://www.nxzwnews.net/"))

//青海
qh.webs.push(new TVWeb("青海长云网","青海","http://www.qhbtv.com/"))
qh.webs.push(new TVWeb("西宁网络电视台","青海西宁","https://www.xntv.tv/"))
qh.webs.push(new TVWeb("海东新闻网","青海海东","http://www.haidongnews.com/"))
qh.webs.push(new TVWeb("海北新闻网","青海海北","http://www.haibeinews.com/"))
qh.webs.push(new TVWeb("黄南新闻网","青海黄南","https://www.qhhnnews.com/"))
qh.webs.push(new TVWeb("海南州网络广播电视台","青海海南","http://www.hnzzzzzdst.com/"))
qh.webs.push(new TVWeb("果洛新闻网","青海果洛","http://www.guoluonews.com/"))
qh.webs.push(new TVWeb("玉树州新闻网","青海玉树","http://www.yushunews.com/"))
qh.webs.push(new TVWeb("海西新闻网","青海海西","http://www.haixinews.com/"))

//山东
sd.webs.push(new TVWeb("齐鲁网","山东","http://www.iqilu.com/"))
sd.webs.push(new TVWeb("济南网","山东济南","https://www.ijntv.cn/"))
sd.webs.push(new TVWeb("青岛网络广播电视台","山东青岛","http://www.qtv.com.cn/"))
sd.webs.push(new TVWeb("中华宽带网","山东淄博","http://www.zbrt.com/"))
sd.webs.push(new TVWeb("鲁南传媒网","山东枣庄","http://tv.lncm.cn/"))
sd.webs.push(new TVWeb("东营市广播电视台","山东东营","http://www.hhek.cn/"))
sd.webs.push(new TVWeb("烟台网络广播电视台","山东烟台","http://www.yantaitv.cn/"))
sd.webs.push(new TVWeb("潍坊传媒网","山东潍坊","http://www.wfcmw.cn/"))
sd.webs.push(new TVWeb("济宁新闻网","山东济宁","https://www.jnnews.tv/"))
sd.webs.push(new TVWeb("泰山网","山东泰安","http://www.1545ts.com/"))
sd.webs.push(new TVWeb("威海传媒网","山东威海","http://www.weihai.tv/"))
sd.webs.push(new TVWeb("日照网","山东日照","http://www.rzw.com.cn/"))
sd.webs.push(new TVWeb("滨州网","山东滨州","https://www.binzhouw.com/"))
sd.webs.push(new TVWeb("大略网","山东德州","http://www.dztv.tv/"))
sd.webs.push(new TVWeb("聊城视窗网","山东聊城","http://www.lcbtv.com/"))
sd.webs.push(new TVWeb("爱临沂网","山东临沂","https://www.ilinyi.net/"))
sd.webs.push(new TVWeb("菏泽广播电视台","山东菏泽","http://www.hznet.tv/"))

//山西
sx.webs.push(new TVWeb("山西网络广播电视台","山西","http://www.sxrtv.com/"))
sx.webs.push(new TVWeb("太原台","山西太原","http://ty.cutv.com/"))
sx.webs.push(new TVWeb("大同网络广播电视台","山西大同",""))
sx.webs.push(new TVWeb("朔州视听网","山西朔州","http://www.sxsztv.com/"))
sx.webs.push(new TVWeb("忻州广播电视网","山西忻州","http://www.0350tv.cn/"))
sx.webs.push(new TVWeb("阳泉网络广播电视台","山西阳泉","https://www.yqrtv.com/"))
sx.webs.push(new TVWeb("吕梁广播电视网","山西吕梁","https://www.llbtv.com/"))
sx.webs.push(new TVWeb("晋中广播电视台 视听网","山西晋中","https://www.jztvnews.com/"))
sx.webs.push(new TVWeb("长治新闻网","山西长治","http://www.changzhinews.com/"))
sx.webs.push(new TVWeb("晋城新闻网","山西晋城","http://www.jcnews.com.cn/"))
sx.webs.push(new TVWeb("临汾广电网","山西临汾","http://www.lfgdw.cn/"))
sx.webs.push(new TVWeb("运城视听网","山西运城","http://www.0359tv.com/"))

//陕西
sn.webs.push(new TVWeb("陕西广播电视台","陕西","http://www.sxtvs.com/"))
sn.webs.push(new TVWeb("西安网络广播电视台","陕西西安","http://www.xantv.cn/"))
sn.webs.push(new TVWeb("宝鸡电视台","陕西宝鸡","http://www.tvbaoji.com/"))
sn.webs.push(new TVWeb("咸阳视听网","陕西咸阳","http://www.xybtv.com/"))
sn.webs.push(new TVWeb("铜川新闻网","陕西铜川","http://www.tcrbs.com/"))
sn.webs.push(new TVWeb("渭南网络电视台","陕西渭南","http://www.wntvs.com/"))
sn.webs.push(new TVWeb("延安新闻网","陕西延安","http://www.yanews.cn/"))
sn.webs.push(new TVWeb("榆林视听","陕西榆林","http://v.ylrb.com/"))
sn.webs.push(new TVWeb("汉中广播电视台","陕西汉中","http://www.hzrtvs.com"))
sn.webs.push(new TVWeb("安康新闻网","陕西安康市","http://www.akxw.cn/"))
sn.webs.push(new TVWeb("商洛网视","陕西商洛","http://www.sltvs.cn/"))

//上海
sh.webs.push(new TVWeb("上海广播电视台","上海","https://www.smg.cn/"))

//四川
sc.webs.push(new TVWeb("四川广播电视台","四川","https://www.sctv.com/"))
sc.webs.push(new TVWeb("无限成都","四川成都","http://www.cdtv.cn/"))
sc.webs.push(new TVWeb("自贡市广播电视台","四川自贡","http://www.zgbctv.com/"))
sc.webs.push(new TVWeb("攀枝花广电传媒网","四川攀枝花","https://www.pzhgd.com/"))
sc.webs.push(new TVWeb("大听网","四川泸州","http://luzhoubs.com/"))
sc.webs.push(new TVWeb("德阳传媒网","四川德阳","https://scdytv.com/"))
sc.webs.push(new TVWeb("迈尚网","四川绵阳","http://www.myntv.cn/"))
sc.webs.push(new TVWeb("大话利州","四川广元","http://www.dzsm.com/"))
sc.webs.push(new TVWeb("遂宁新闻网","四川遂宁","http://www.snxw.com/"))
sc.webs.push(new TVWeb("甜橙网","四川内江","https://www.scnj.tv/"))
sc.webs.push(new TVWeb("乐山网络电视","四川乐山","http://www.leshantv.net/"))
sc.webs.push(new TVWeb("南充广播电视台","四川南充","https://www.ncntv.com.cn/"))
sc.webs.push(new TVWeb("眉山市广播电视台","四川眉山","http://www.scmstv.cn/"))
sc.webs.push(new TVWeb("宜宾电视台","四川宜宾","http://www.ybtv.cc/"))
sc.webs.push(new TVWeb("广安新闻网","四川广安","http://www.gatv.com.cn/"))
sc.webs.push(new TVWeb("达州新闻网","四川达州","http://www.dzxw.net/"))
sc.webs.push(new TVWeb("无线雅安","四川雅安","https://www.wuxianyaan.com/"))
sc.webs.push(new TVWeb("巴中网","四川巴中","http://www.bzgd.com/"))
sc.webs.push(new TVWeb("资阳网","四川资阳","http://www.sczytv.com/"))
sc.webs.push(new TVWeb("阿坝新闻网","四川阿坝","http://www.aba-news.com.cn/"))
sc.webs.push(new TVWeb("凉山新闻网","四川凉山","http://www.ls666.com/"))
//天津
tj.webs.push(new TVWeb("天津广播电视台","天津","http://tjtv.enorth.com.cn/"))
//西藏
xz.webs.push(new TVWeb("中国西藏之声网","西藏","http://www.vtibet.cn/"))
xz.webs.push(new TVWeb("拉萨广播电视网","西藏拉萨","http://www.lasatv.cn/"))
xz.webs.push(new TVWeb("日喀则新闻网","西藏日喀则","http://www.rkzw.cn/"))
xz.webs.push(new TVWeb("今日西藏昌都","西藏昌都","http://www.xzcd.com/"))
xz.webs.push(new TVWeb("西藏林芝网","西藏林芝","http://www.linzhinews.com/"))
xz.webs.push(new TVWeb("山南网","西藏山南","http://www.xzsnw.com/"))
xz.webs.push(new TVWeb("西藏那曲新闻网","西藏那曲","http://www.xznqnews.com/"))
//新疆
xj.webs.push(new TVWeb("丝路视听","新疆","http://www.xjtvs.com.cn/"))
xj.webs.push(new TVWeb("红山网","新疆乌鲁木齐","http://www.hongshannet.cn/"))
xj.webs.push(new TVWeb("克拉玛依网","新疆克拉玛依","https://www.kelamayi.com.cn/"))
xj.webs.push(new TVWeb("吐鲁番广播电视台","新疆吐鲁番","http://www.tlfgbdt.com/"))
xj.webs.push(new TVWeb("今日哈密网","新疆哈密","http://www.jrhm.cn/"))
xj.webs.push(new TVWeb("阿克苏新闻网","新疆阿克苏","http://ask.aksxw.com/"))
xj.webs.push(new TVWeb("中国喀什网","新疆喀什","http://www.zgkashi.com/"))
xj.webs.push(new TVWeb("中国昌吉网","新疆昌吉","http://www.cjxww.cn/"))
xj.webs.push(new TVWeb("博尔塔拉新闻网","新疆博尔塔拉","http://www.boznews.cn/"))

//云南
yn.webs.push(new TVWeb("云视网","云南","http://www.yntv.cn/"))
yn.webs.push(new TVWeb("昆明广播电视台","云南昆明","http://www.kunmingbc.com/"))
yn.webs.push(new TVWeb("曲靖新闻网","云南曲靖","http://www.qjrb.cn/"))
yn.webs.push(new TVWeb("玉溪广播电视新闻网","云南玉溪","http://www.yxtv.cn/"))
yn.webs.push(new TVWeb("昭通新闻网","云南昭通","https://www.ztnews.net/"))
yn.webs.push(new TVWeb("保山市广播电视台","云南保山",""))
yn.webs.push(new TVWeb("丽江热线","云南丽江","https://www.lijiangtv.com/"))
yn.webs.push(new TVWeb("普洱广播网","云南普洱","http://www.pegbw.com/"))
yn.webs.push(new TVWeb("临沧新闻网","云南临沧","http://www.lincangnews.cn/"))
yn.webs.push(new TVWeb("德宏网","云南德宏","https://www.dehong.gov.cn/"))
yn.webs.push(new TVWeb("怒江大峡谷网","云南怒江","https://www.nujiang.cn/"))
yn.webs.push(new TVWeb("云南楚雄网","云南楚雄","https://www.chuxiong.cn/"))
yn.webs.push(new TVWeb("文山新闻网","云南文山","http://www.wsnews.com.cn/"))
yn.webs.push(new TVWeb("西双版纳广播电视网","云南西双版纳","http://www.xsbnrtv.cn/"))
//浙江
zj.webs.push(new TVWeb("新蓝网","浙江","http://www.cztv.com/"))
zj.webs.push(new TVWeb("葫芦网","浙江杭州","https://www.hoolo.tv/"))
zj.webs.push(new TVWeb("宁波观广电网","浙江宁波","http://www.nbtv.cn/"))
zj.webs.push(new TVWeb("东海网","浙江温州","http://www.wztv.cn/"))
zj.webs.push(new TVWeb("绍兴网","浙江绍兴","http://www.shaoxing.com.cn/"))
zj.webs.push(new TVWeb("湖州在线","浙江湖州","http://www.hz66.com/"))
zj.webs.push(new TVWeb("嘉兴在线","浙江嘉兴","http://www.cnjxol.com/"))
zj.webs.push(new TVWeb("金华新闻网","浙江金华","https://www.jhnews.com.cn/"))
zj.webs.push(new TVWeb("衢州传媒网","浙江衢州","https://www.qz123.com/"))
zj.webs.push(new TVWeb("台州在线","浙江台州","http://www.576tv.com/"))
zj.webs.push(new TVWeb("丽水网","浙江丽水","http://www.lsnews.com.cn/"))
zj.webs.push(new TVWeb("舟山网","浙江舟山","http://www.zhoushan.cn/"))
zj.webs.push(new TVWeb("","浙江",""))

//台湾
tw.webs.push(new TVWeb("TVBS","台湾","https://www.tvbs.com.tw/"))

//其他
noAut.webs.push(new TVWeb("星空华文国际传媒","其他","http://xk.kgdns.cn/"))